services:
  - type: web
    name: document-scanner-backend
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    root: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
